blank_issues_enabled: true
contact_links:
  - name: Ideas y solicitudes de funciones
    url: https://github.com/upptime/upptime/discussions/new?category=ideas
    about: Sugiere una idea para este proyecto
  - name: Preguntas
    url: https://github.com/upptime/upptime/discussions/new?category=q-a
    about: Preguntas y respuestas aqu√≠